//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sekolah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Guru()
        {
            this.Jadwals = new HashSet<Jadwal>();
        }
    
        public int IdGuru { get; set; }
        public string NamaGuru { get; set; }
        public string Alamat { get; set; }
        public string TahunMulaiMengajar { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jadwal> Jadwals { get; set; }
    }
}
