//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sekolah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jadwal
    {
        public int IdJadwal { get; set; }
        public string Kelas { get; set; }
        public string Waktu { get; set; }
        public string IdMapel { get; set; }
        public int IdGuru { get; set; }
    
        public virtual Guru Guru { get; set; }
        public virtual Mapel Mapel { get; set; }
    }
}
